import { FitnessCategory } from '@/shared/generated/prisma/enums';

export const FITNESS_CATEGORY_LABELS: Record<FitnessCategory, string> = {
  [FitnessCategory.Strength]: 'Сила',
  [FitnessCategory.Cardio]: 'Кардио',
  [FitnessCategory.Flexibility]: 'Гибкость',
  [FitnessCategory.Endurance]: 'Выносливость',
  [FitnessCategory.Mobility]: 'Мобильность',
  [FitnessCategory.Balance]: 'Баланс',
  [FitnessCategory.Speed]: 'Скорость',
  [FitnessCategory.Agility]: 'Ловкость',
  [FitnessCategory.Power]: 'Взрывная сила',
  [FitnessCategory.WeightLoss]: 'Похудение',
  [FitnessCategory.MuscleGain]: 'Набор массы',
  [FitnessCategory.Nutrition]: 'Питание',
  [FitnessCategory.Hydration]: 'Водный баланс',
  [FitnessCategory.Sleep]: 'Сон',
  [FitnessCategory.Recovery]: 'Восстановление',
  [FitnessCategory.MentalHealth]: 'Ментальное здоровье',
  [FitnessCategory.Mindfulness]: 'Осознанность',
  [FitnessCategory.DailySteps]: 'Ежедневная активность',
  [FitnessCategory.Posture]: 'Осанка',
  [FitnessCategory.Yoga]: 'Йога',
  [FitnessCategory.Calisthenics]: 'Воркаут',
  [FitnessCategory.Running]: 'Бег',
  [FitnessCategory.Cycling]: 'Велоспорт',
  [FitnessCategory.Swimming]: 'Плавание',
  [FitnessCategory.Dance]: 'Танцы',
  [FitnessCategory.MartialArts]: 'Единоборства',
};
